from fastapi import APIRouter, HTTPException, status
from typing import List, Optional
from app.api.v1.onboarding import DOCTORS_DATABASE

router = APIRouter(prefix="/doctors", tags=["Doctors"])

SEED_DOCTORS = {
    "dr-rahul-sharma": {
        "id": "d1111111-1111-1111-1111-111111111111",
        "slug": "dr-rahul-sharma",
        "title": "Dr.",
        "full_name": "Dr. Rahul Sharma",
        "medical_council_reg_number": "UKMC-8942-2012",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Dermatology, Venereology & Leprosy)",
        "specialization": "Dermatologist",
        "sub_specializations": ["Acne Specialist", "Cosmetic Laser Surgery", "Hair Loss Therapy"],
        "years_of_experience": 12,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Dr. Rahul Sharma is a senior consultant dermatologist with over 12 years of clinical expertise in treating chronic acne, psoriasis, and laser aesthetic procedures. Committed to evidence-based skincare.",
        "consultation_fee": 600.00,
        "followup_fee": 300.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Skin Consultation", "fee": 600},
            {"name": "Chemical Peel & Acne Treatment", "fee": 1500},
            {"name": "Laser Scar Reduction", "fee": 2500},
            {"name": "PRP Hair Loss Therapy", "fee": 3500}
        ],
        "verification_status": "verified",
        "rating": 4.9,
        "total_reviews": 142,
        "clinic_name": "Derma Care Skin & Laser Centre",
        "clinic_slug": "derma-care-dehradun",
        "clinic_address": "14, Rajpur Road, Near Ashley Hall, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 02:00 PM, 05:00 PM - 08:30 PM"
    },
    "dr-aditi-joshi": {
        "id": "d2222222-2222-2222-2222-222222222222",
        "slug": "dr-aditi-joshi",
        "title": "Dr.",
        "full_name": "Dr. Aditi Joshi",
        "medical_council_reg_number": "UDC-4120-2016",
        "medical_council_state": "Uttarakhand Dental Council",
        "qualification_summary": "BDS, MDS (Conservative Dentistry & Endodontics)",
        "specialization": "Dentist",
        "sub_specializations": ["Painless Root Canal", "Cosmetic Veneers", "Dental Implants"],
        "years_of_experience": 8,
        "languages_spoken": ["English", "Hindi", "Garhwali"],
        "bio": "Dr. Aditi Joshi is a leading endodontist known for painless single-sitting root canals and digital smile design in Dehradun.",
        "consultation_fee": 400.00,
        "followup_fee": 0.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Dental Checkup & Digital X-Ray", "fee": 400},
            {"name": "Single Sitting Painless RCT", "fee": 3000},
            {"name": "Teeth Whitening", "fee": 3500},
            {"name": "Dental Implants Consultation", "fee": 800}
        ],
        "verification_status": "verified",
        "rating": 4.8,
        "total_reviews": 98,
        "clinic_name": "Smile Craft Multi-Speciality Dental",
        "clinic_slug": "smile-craft-dental",
        "clinic_address": "42, EC Road, Near Survey Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 01:30 PM, 04:30 PM - 08:00 PM"
    },
    "dr-vikram-sethi": {
        "id": "d3333333-3333-3333-3333-333333333333",
        "slug": "dr-vikram-sethi",
        "title": "Dr.",
        "full_name": "Dr. Vikram Sethi",
        "medical_council_reg_number": "UKMC-6214-2009",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, DCH, DNB (Pediatrics)",
        "specialization": "Pediatrician",
        "sub_specializations": ["Newborn Intensive Care", "Childhood Asthma", "Vaccination"],
        "years_of_experience": 15,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Senior child specialist providing gentle, compassionate pediatric healthcare, newborn care, and complete childhood immunization schedules.",
        "consultation_fee": 500.00,
        "followup_fee": 200.00,
        "followup_validity_days": 5,
        "services_offered": [
            {"name": "Child OPD Consultation", "fee": 500},
            {"name": "Vaccination Administration", "fee": 200},
            {"name": "Growth & Milestones Assessment", "fee": 600}
        ],
        "verification_status": "verified",
        "rating": 4.95,
        "total_reviews": 210,
        "clinic_name": "Dron Child & Newborn Health Centre",
        "clinic_slug": "dron-child-clinic",
        "clinic_address": "88, Chakrata Road, Near Ballupur Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 09:30 AM - 01:00 PM, 05:00 PM - 08:30 PM"
    },
    "dr-arvind-rawat": {
        "id": "d4444444-4444-4444-4444-444444444444",
        "slug": "dr-arvind-rawat",
        "title": "Dr.",
        "full_name": "Dr. Arvind Rawat",
        "medical_council_reg_number": "UKMC-4819-2008",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (General Medicine)",
        "specialization": "General Physician",
        "sub_specializations": ["Internal Medicine", "Diabetes Care", "Hypertension"],
        "years_of_experience": 16,
        "languages_spoken": ["English", "Hindi", "Garhwali"],
        "bio": "Senior Consultant in Internal Medicine with 16 years of clinical experience managing diabetes reversal protocols, hypertension, viral illnesses, and preventive health audits.",
        "consultation_fee": 500.00,
        "followup_fee": 250.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "General Medicine Consultation", "fee": 500},
            {"name": "Diabetes Reversal & Diet Mapping", "fee": 900},
            {"name": "ECG + Vitals Screening", "fee": 350},
            {"name": "Infection & Viral Treatment Plan", "fee": 500}
        ],
        "verification_status": "verified",
        "rating": 4.92,
        "total_reviews": 184,
        "clinic_name": "Doon Family Health & Diabetes Care",
        "clinic_slug": "doon-family-health",
        "clinic_address": "12, Saharanpur Road, Near Patel Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 09:00 AM - 01:30 PM, 05:00 PM - 08:30 PM"
    },
    "dr-priya-nair": {
        "id": "d5555555-5555-5555-5555-555555555555",
        "slug": "dr-priya-nair",
        "title": "Dr.",
        "full_name": "Dr. Priya Nair",
        "medical_council_reg_number": "UKMC-3912-2010",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Medicine), DM (Cardiology), FACC",
        "specialization": "Cardiologist",
        "sub_specializations": ["Interventional Cardiology", "Echocardiography", "Preventive Heart Health"],
        "years_of_experience": 14,
        "languages_spoken": ["English", "Hindi", "Malayalam"],
        "bio": "Interventional Cardiologist specialized in coronary artery disease, post-angioplasty care, heart failure, 2D Echocardiography, and preventive cardiac wellness.",
        "consultation_fee": 800.00,
        "followup_fee": 400.00,
        "followup_validity_days": 10,
        "services_offered": [
            {"name": "Cardiology Consultation", "fee": 800},
            {"name": "2D Color Doppler Echo", "fee": 2200},
            {"name": "TMT Stress Test", "fee": 1800}
        ],
        "verification_status": "verified",
        "rating": 4.96,
        "total_reviews": 167,
        "clinic_name": "Himalayan Heart & Vascular Clinic",
        "clinic_slug": "himalayan-heart-clinic",
        "clinic_address": "56, Rajpur Road, Opp. Hotel Madhuban, Dehradun",
        "opd_timings": "Mon - Sat: 11:00 AM - 03:00 PM, 05:30 PM - 08:30 PM"
    },
    "dr-rajesh-semwal": {
        "id": "d6666666-6666-6666-6666-666666666666",
        "slug": "dr-rajesh-semwal",
        "title": "Dr.",
        "full_name": "Dr. Rajesh Semwal",
        "medical_council_reg_number": "UKMC-5102-2006",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MS (Orthopedics), MCh (Joint Replacement)",
        "specialization": "Orthopedic Surgeon",
        "sub_specializations": ["Robotic Joint Replacement", "Sports Ligament Repair", "Spine Sciatica"],
        "years_of_experience": 18,
        "languages_spoken": ["English", "Hindi", "Garhwali"],
        "bio": "Renowned orthopedic & spine surgeon specializing in robotic knee and hip joint replacements, sports ligament repairs (ACL/PCL), sciatica, and complex trauma fractures.",
        "consultation_fee": 600.00,
        "followup_fee": 300.00,
        "followup_validity_days": 10,
        "services_offered": [
            {"name": "Orthopedic OPD Consultation", "fee": 600},
            {"name": "Joint Injection (Hyaluronic/Steroid)", "fee": 1500},
            {"name": "Spine & Sciatica Assessment", "fee": 600}
        ],
        "verification_status": "verified",
        "rating": 4.92,
        "total_reviews": 230,
        "clinic_name": "Doon Ortho & Joint Spine Clinic",
        "clinic_slug": "doon-ortho-spine",
        "clinic_address": "24, Ballupur Chowk, Chakrata Road, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 02:00 PM, 05:00 PM - 08:00 PM"
    },
    "dr-meenakshi-sundaram": {
        "id": "d7777777-7777-7777-7777-777777777777",
        "slug": "dr-meenakshi-sundaram",
        "title": "Dr.",
        "full_name": "Dr. Meenakshi Sundaram",
        "medical_council_reg_number": "UKMC-7890-2011",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MS (Obstetrics & Gynecology), DGO",
        "specialization": "Gynecologist",
        "sub_specializations": ["High-Risk Pregnancy", "PCOS / PCOD Care", "Infertility Workup"],
        "years_of_experience": 15,
        "languages_spoken": ["English", "Hindi", "Tamil"],
        "bio": "Compassionate obstetrician & gynecologist providing comprehensive prenatal care, high-risk pregnancy management, painless normal deliveries, and holistic PCOS/PCOD reversal.",
        "consultation_fee": 600.00,
        "followup_fee": 300.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Gynecology & Pregnancy Consultation", "fee": 600},
            {"name": "Pap Smear & Cervical Screening", "fee": 800},
            {"name": "PCOS Lifestyle & Endocrine Mapping", "fee": 1000}
        ],
        "verification_status": "verified",
        "rating": 4.94,
        "total_reviews": 195,
        "clinic_name": "Motherhood Care & Fertility Clinic",
        "clinic_slug": "motherhood-care-dehradun",
        "clinic_address": "31, Dalanwala, Circular Road, Dehradun",
        "opd_timings": "Mon - Sat: 10:30 AM - 02:30 PM, 05:00 PM - 07:30 PM"
    },
    "dr-amit-bansal": {
        "id": "d8888888-8888-8888-8888-888888888888",
        "slug": "dr-amit-bansal",
        "title": "Dr.",
        "full_name": "Dr. Amit Bansal",
        "medical_council_reg_number": "UKMC-6543-2013",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MS (ENT / Otorhinolaryngology)",
        "specialization": "ENT Specialist",
        "sub_specializations": ["Endoscopic Sinus Surgery", "Micro Ear Surgery", "Vertigo Tinnitus"],
        "years_of_experience": 11,
        "languages_spoken": ["English", "Hindi"],
        "bio": "ENT & Head-Neck surgeon with advanced expertise in endoscopic sinus surgery, micro-ear surgery for eardrum perforation, vertigo balance therapy, and pediatric adenoid removal.",
        "consultation_fee": 500.00,
        "followup_fee": 200.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "ENT Consultation & Otoscopy", "fee": 500},
            {"name": "Diagnostic Nasal Endoscopy", "fee": 1200}
        ],
        "verification_status": "verified",
        "rating": 4.85,
        "total_reviews": 115,
        "clinic_name": "Bansal ENT & Micro-Ear Care Centre",
        "clinic_slug": "bansal-ent-centre",
        "clinic_address": "18, Subhash Road, Near Clock Tower, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 02:00 PM, 05:00 PM - 08:00 PM"
    },
    "dr-sunita-bhatt": {
        "id": "d9999999-9999-9999-9999-999999999999",
        "slug": "dr-sunita-bhatt",
        "title": "Dr.",
        "full_name": "Dr. Sunita Bhatt",
        "medical_council_reg_number": "UKMC-4921-2010",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MS (Ophthalmology), FICO (UK)",
        "specialization": "Ophthalmologist",
        "sub_specializations": ["Blade-Free Cataract", "Lasik Eye Surgery", "Glaucoma Screening"],
        "years_of_experience": 13,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Consultant Eye Surgeon and Lasik specialist recognized for micro-incision blade-free cataract surgeries, diabetic retinopathy screening, and pediatric vision correction.",
        "consultation_fee": 500.00,
        "followup_fee": 250.00,
        "followup_validity_days": 14,
        "services_offered": [
            {"name": "Comprehensive Eye Exam & Slit Lamp", "fee": 500},
            {"name": "Dilated Retina Examination", "fee": 800}
        ],
        "verification_status": "verified",
        "rating": 4.88,
        "total_reviews": 134,
        "clinic_name": "Drishti Netralaya & Laser Eye Centre",
        "clinic_slug": "drishti-netralaya",
        "clinic_address": "74, Haridwar Road, Near Rispana Bridge, Dehradun",
        "opd_timings": "Mon - Sat: 09:30 AM - 01:30 PM, 04:30 PM - 07:30 PM"
    },
    "dr-tarun-deep-singh": {
        "id": "daaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        "slug": "dr-tarun-deep-singh",
        "title": "Dr.",
        "full_name": "Dr. Tarun Deep Singh",
        "medical_council_reg_number": "UKMC-3210-2012",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Medicine), DM (Neurology)",
        "specialization": "Neurologist",
        "sub_specializations": ["Refractory Migraines", "Stroke Prevention", "Epilepsy"],
        "years_of_experience": 12,
        "languages_spoken": ["English", "Hindi", "Punjabi"],
        "bio": "Senior Neurologist managing refractory migraines, stroke rehabilitation, epilepsy management, Parkinson's tremors, peripheral neuropathies, and nerve conduction studies.",
        "consultation_fee": 900.00,
        "followup_fee": 500.00,
        "followup_validity_days": 14,
        "services_offered": [
            {"name": "Neurology Consultation", "fee": 900},
            {"name": "Digital EEG (Brain Wave Mapping)", "fee": 2000}
        ],
        "verification_status": "verified",
        "rating": 4.91,
        "total_reviews": 148,
        "clinic_name": "Doon Brain, Spine & Nerve Clinic",
        "clinic_slug": "doon-brain-nerve",
        "clinic_address": "52, GMS Road, Near Kamla Palace, Dehradun",
        "opd_timings": "Mon - Sat: 11:00 AM - 03:00 PM, 05:00 PM - 08:00 PM"
    },
    "dr-kavita-negi": {
        "id": "dbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        "slug": "dr-kavita-negi",
        "title": "Dr.",
        "full_name": "Dr. Kavita Negi",
        "medical_council_reg_number": "UKMC-7193-2014",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Medicine), DM (Gastroenterology)",
        "specialization": "Gastroenterologist",
        "sub_specializations": ["Endoscopy", "Fatty Liver", "IBS & GERD"],
        "years_of_experience": 10,
        "languages_spoken": ["English", "Hindi", "Garhwali"],
        "bio": "Gastroenterologist and Hepatologist specialized in therapeutic endoscopy, fatty liver disease reversal, chronic acidity (GERD), irritable bowel syndrome (IBS), and gallstones.",
        "consultation_fee": 700.00,
        "followup_fee": 350.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Gastro Consultation", "fee": 700},
            {"name": "Diagnostic Video Endoscopy", "fee": 2800}
        ],
        "verification_status": "verified",
        "rating": 4.87,
        "total_reviews": 122,
        "clinic_name": "Gastro Care & Liver Health Clinic",
        "clinic_slug": "gastro-care-dehradun",
        "clinic_address": "19, Patel Nagar, Saharanpur Road, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 02:00 PM, 05:00 PM - 08:00 PM"
    },
    "dr-harish-pant": {
        "id": "dccccccc-cccc-cccc-cccc-cccccccccccc",
        "slug": "dr-harish-pant",
        "title": "Dr.",
        "full_name": "Dr. Harish Pant",
        "medical_council_reg_number": "UKMC-5829-2009",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Pulmonary Medicine), FCCP (USA)",
        "specialization": "Pulmonologist",
        "sub_specializations": ["Asthma Care", "Allergy Testing", "COPD Sleep Apnea"],
        "years_of_experience": 14,
        "languages_spoken": ["English", "Hindi", "Kumaoni"],
        "bio": "Leading chest physician and allergy specialist. Expertise in bronchial asthma, allergic bronchitis, chronic COPD, post-COVID lung recovery, and sleep apnea snoring diagnostics.",
        "consultation_fee": 600.00,
        "followup_fee": 300.00,
        "followup_validity_days": 10,
        "services_offered": [
            {"name": "Chest & Pulmonary Consultation", "fee": 600},
            {"name": "Spirometry / PFT Lung Capacity", "fee": 900}
        ],
        "verification_status": "verified",
        "rating": 4.89,
        "total_reviews": 153,
        "clinic_name": "Doon Respiratory & Allergy Clinic",
        "clinic_slug": "doon-respiratory-clinic",
        "clinic_address": "65, Chakrata Road, Opp. Kishan Nagar Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 09:30 AM - 01:30 PM, 05:00 PM - 08:30 PM"
    },
    "dr-ritu-dangwal": {
        "id": "dddddddd-dddd-dddd-dddd-dddddddddddd",
        "slug": "dr-ritu-dangwal",
        "title": "Dr.",
        "full_name": "Dr. Ritu Dangwal",
        "medical_council_reg_number": "UKMC-8104-2015",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Psychiatry)",
        "specialization": "Psychiatrist",
        "sub_specializations": ["Anxiety & Panic", "Depression Therapy", "Sleep Disorders"],
        "years_of_experience": 9,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Compassionate psychiatrist and mental health advocate specialized in clinical depression, panic and generalized anxiety disorders, adult ADHD, insomnia, and stress burnout.",
        "consultation_fee": 800.00,
        "followup_fee": 500.00,
        "followup_validity_days": 14,
        "services_offered": [
            {"name": "Psychiatric Clinical Consultation (45m)", "fee": 800},
            {"name": "Cognitive Stress Counseling", "fee": 1000}
        ],
        "verification_status": "verified",
        "rating": 4.93,
        "total_reviews": 89,
        "clinic_name": "Mind Space Mental Wellness Clinic",
        "clinic_slug": "mind-space-clinic",
        "clinic_address": "21, Rajpur Road, Near Orient Cinema, Dehradun",
        "opd_timings": "Mon - Sat: 11:00 AM - 03:00 PM, 05:00 PM - 08:00 PM"
    },
    "dr-sanjay-chamoli": {
        "id": "deeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
        "slug": "dr-sanjay-chamoli",
        "title": "Dr.",
        "full_name": "Dr. Sanjay Chamoli",
        "medical_council_reg_number": "UKMC-4512-2007",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MS (Surgery), MCh (Urology)",
        "specialization": "Urologist",
        "sub_specializations": ["Laser Kidney Stone", "Prostate TURP", "UTI Clinic"],
        "years_of_experience": 15,
        "languages_spoken": ["English", "Hindi", "Garhwali"],
        "bio": "Senior Urologist and Andrologist with extensive experience in laser kidney stone removal (RIRS/PCNL), enlarged prostate treatment (TURP/HOLEP), and urinary tract infections.",
        "consultation_fee": 750.00,
        "followup_fee": 400.00,
        "followup_validity_days": 10,
        "services_offered": [
            {"name": "Urology Consultation", "fee": 750},
            {"name": "Uroflowmetry Test", "fee": 800}
        ],
        "verification_status": "verified",
        "rating": 4.9,
        "total_reviews": 176,
        "clinic_name": "Doon Uro-Stone & Laser Centre",
        "clinic_slug": "doon-uro-stone",
        "clinic_address": "38, Saharanpur Road, Near Prince Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 02:00 PM, 05:30 PM - 08:30 PM"
    },
    "dr-vivek-thapliyal": {
        "id": "dfffffff-ffff-ffff-ffff-ffffffffffff",
        "slug": "dr-vivek-thapliyal",
        "title": "Dr.",
        "full_name": "Dr. Vivek Thapliyal",
        "medical_council_reg_number": "UKMC-3901-2011",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (Medicine), DM (Medical Oncology), ESMO Certified",
        "specialization": "Oncologist",
        "sub_specializations": ["Chemotherapy", "Targeted Immunotherapy", "Cancer Screening"],
        "years_of_experience": 13,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Senior Medical Oncologist specializing in targeted chemotherapy protocols, immunotherapy, comprehensive cancer screenings, second opinions, and palliative symptom care.",
        "consultation_fee": 1000.00,
        "followup_fee": 500.00,
        "followup_validity_days": 14,
        "services_offered": [
            {"name": "Oncology Expert Consultation", "fee": 1000},
            {"name": "Chemotherapy Daycare Protocol", "fee": 3500}
        ],
        "verification_status": "verified",
        "rating": 4.95,
        "total_reviews": 110,
        "clinic_name": "Doon Comprehensive Cancer Care Clinic",
        "clinic_slug": "doon-cancer-care",
        "clinic_address": "102, Haridwar Road, Near Kargi Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 11:30 AM - 03:30 PM, 05:30 PM - 08:00 PM"
    },
    "vaidya-rameshwar-prasad": {
        "id": "d0000000-0000-0000-0000-000000000001",
        "slug": "vaidya-rameshwar-prasad",
        "title": "Vaidya",
        "full_name": "Vaidya Rameshwar Prasad",
        "medical_council_reg_number": "UBC-2109-2004",
        "medical_council_state": "Uttarakhand Ayurvedic Council",
        "qualification_summary": "BAMS, MD (Ayurveda Panchakarma)",
        "specialization": "Ayurvedic Physician",
        "sub_specializations": ["Nadi Pariksha", "Panchakarma Detox", "Joint Disorders"],
        "years_of_experience": 20,
        "languages_spoken": ["English", "Hindi", "Sanskrit"],
        "bio": "Traditional Ayurvedic Practitioner and Nadi Pariksha diagnostician. Offers classical Panchakarma detox, chronic joint pain therapies, and gut balancing herbal formulations.",
        "consultation_fee": 400.00,
        "followup_fee": 200.00,
        "followup_validity_days": 14,
        "services_offered": [
            {"name": "Ayurvedic Nadi Pariksha Consultation", "fee": 400},
            {"name": "Shirodhara Relaxation Therapy", "fee": 1800}
        ],
        "verification_status": "verified",
        "rating": 4.91,
        "total_reviews": 165,
        "clinic_name": "AyurVeda Health & Panchakarma Kendra",
        "clinic_slug": "ayurveda-panchakarma-kendra",
        "clinic_address": "15, Circular Road, Dalanwala, Dehradun",
        "opd_timings": "Mon - Sat: 08:30 AM - 01:00 PM, 04:30 PM - 07:30 PM"
    },
    "dr-shalini-verma": {
        "id": "d0000000-0000-0000-0000-000000000002",
        "slug": "dr-shalini-verma",
        "title": "Dr.",
        "full_name": "Dr. Shalini Verma",
        "medical_council_reg_number": "UHC-3419-2012",
        "medical_council_state": "Uttarakhand Homeopathic Council",
        "qualification_summary": "BHMS, MD (Homeopathy)",
        "specialization": "Homeopath",
        "sub_specializations": ["Allergic Rhinitis", "Pediatric Immunity", "Chronic Skin"],
        "years_of_experience": 12,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Classical Homeopathic Consultant known for gentle, constitutional cures for recurrent allergic rhinitis, childhood recurrent colds, eczema, migraine, and hormonal imbalances.",
        "consultation_fee": 350.00,
        "followup_fee": 200.00,
        "followup_validity_days": 14,
        "services_offered": [
            {"name": "Homeopathic Case Taking & Consultation", "fee": 350},
            {"name": "2-Week Medication Pack", "fee": 300}
        ],
        "verification_status": "verified",
        "rating": 4.82,
        "total_reviews": 94,
        "clinic_name": "Care Classical Homeopathy Clinic",
        "clinic_slug": "care-homeopathy-clinic",
        "clinic_address": "28, Vasant Vihar, Main Market, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 01:30 PM, 05:00 PM - 08:00 PM"
    },
    "dr-rohan-uniyal": {
        "id": "d0000000-0000-0000-0000-000000000003",
        "slug": "dr-rohan-uniyal",
        "title": "Dr.",
        "full_name": "Dr. Rohan Uniyal (PT)",
        "medical_council_reg_number": "UPC-5612-2016",
        "medical_council_state": "Uttarakhand Physiotherapy Council",
        "qualification_summary": "BPT, MPT (Sports Rehab & Musculoskeletal Orthopedics)",
        "specialization": "Physiotherapist",
        "sub_specializations": ["Post-Surgical Rehab", "Dry Needling", "Spine Posture"],
        "years_of_experience": 8,
        "languages_spoken": ["English", "Hindi", "Garhwali"],
        "bio": "Lead Sports Physiotherapist specializing in post-operative knee and hip rehabilitation, dry needling, cervical spondylosis posture correction, and athletic mobility recovery.",
        "consultation_fee": 400.00,
        "followup_fee": 350.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Physiotherapy Assessment & Consultation", "fee": 400},
            {"name": "Electrotherapy + Ultrasound Session", "fee": 500}
        ],
        "verification_status": "verified",
        "rating": 4.94,
        "total_reviews": 145,
        "clinic_name": "Active Life Physio & Sports Rehab",
        "clinic_slug": "active-life-physio",
        "clinic_address": "50, EC Road, Near Dwarika Store, Dehradun",
        "opd_timings": "Mon - Sat: 08:30 AM - 12:30 PM, 04:30 PM - 08:30 PM"
    },
    "dr-rohit-sureka": {
        "id": "d0000000-0000-0000-0000-000000000004",
        "slug": "dr-rohit-sureka",
        "title": "Dr.",
        "full_name": "Dr Rohit Sureka",
        "medical_council_reg_number": "UKMC-9142-2010",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, DNB (General Medicine), DNB (Gastroenterology)",
        "specialization": "Gastroenterology/Gi Medicine Specialist",
        "sub_specializations": ["Endoscopy", "Colonoscopy", "Fatty Liver", "IBS"],
        "years_of_experience": 15,
        "languages_spoken": ["English", "Hindi"],
        "bio": "Senior Consultant Gastroenterologist with over 15 years of clinical expertise in acid peptic disorders, fatty liver, IBS, endoscopy, colonoscopy, and therapeutic digestive care.",
        "consultation_fee": 999.00,
        "followup_fee": 500.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Gastroenterology Consultation", "fee": 999},
            {"name": "Diagnostic Video Endoscopy", "fee": 2500},
            {"name": "Colonoscopy Screening", "fee": 4000}
        ],
        "verification_status": "verified",
        "rating": 4.95,
        "total_reviews": 184,
        "clinic_name": "DocSphere Direct - Gastro Care",
        "clinic_slug": "docsphere-gastro-dehradun",
        "clinic_address": "14, Rajpur Road, Near Ashley Hall, Dehradun",
        "opd_timings": "Mon - Sat: 09:30 AM - 01:30 PM, 05:00 PM - 08:30 PM"
    },
    "dr-harish-k-c": {
        "id": "d0000000-0000-0000-0000-000000000005",
        "slug": "dr-harish-k-c",
        "title": "Dr.",
        "full_name": "Dr Harish K C",
        "medical_council_reg_number": "UKMC-7819-2009",
        "medical_council_state": "Uttarakhand Medical Council",
        "qualification_summary": "MBBS, MD (General Medicine), DM (Gastroenterology)",
        "specialization": "Gastroenterology/Gi Medicine Specialist",
        "sub_specializations": ["GERD", "Liver Care", "Ulcer Protocol"],
        "years_of_experience": 15,
        "languages_spoken": ["English", "Hindi", "Kannada"],
        "bio": "Renowned digestive medicine and liver care specialist providing evidence-based management of acid reflux, GERD, pancreatitis, and chronic hepatitis.",
        "consultation_fee": 1000.00,
        "followup_fee": 500.00,
        "followup_validity_days": 7,
        "services_offered": [
            {"name": "Digestive & Gastro OPD", "fee": 1000},
            {"name": "Liver Ultrasound Evaluation", "fee": 1800}
        ],
        "verification_status": "verified",
        "rating": 4.88,
        "total_reviews": 125,
        "clinic_name": "DocSphere Clinic, Survey Chowk",
        "clinic_slug": "docsphere-survey-chowk",
        "clinic_address": "42, EC Road, Survey Chowk, Dehradun",
        "opd_timings": "Mon - Sat: 10:00 AM - 02:00 PM, 05:30 PM - 08:30 PM"
    }
}

@router.get("", response_model=List[dict])
def list_doctors(specialization: Optional[str] = None, city: Optional[str] = None):
    results = []
    # Combine seed and dynamic doctors
    all_docs = {**SEED_DOCTORS, **DOCTORS_DATABASE}
    for doc in all_docs.values():
        if specialization and specialization.lower() not in doc["specialization"].lower():
            continue
        results.append(doc)
    return results

@router.get("/{slug}")
def get_doctor_profile(slug: str):
    all_docs = {**SEED_DOCTORS, **DOCTORS_DATABASE}
    doc = all_docs.get(slug)
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Doctor profile not found.")
    return doc
